### PR TITLE
fix(statusBar): multi-lang training status logic

### LINKED ISSUE #332: [BUG]: Training status not showing up
When using a multi-language bot, the training status is sometimes not available for certain languages making it hard for users to know if a training exists on the server.
Screen Shot 2022-04-06 at 11 33 22 AM

This image is the result when both languages are trained

### PR DESCRIPTION
**Pull request by EFF**
I mainly did 2 things here:

1- fix issue where a user couldn't see the training status of a 2nd language
2- make this little brain go away, it was driving me nuts.

Concretely I got rid of the redux store for training status as it wasn't used anywhere else than in the statusBar, it was introducing too many unnecessary layer of complexity.
I also re-implemented the "train status service" as this was one of the cause. I also needed to use a reducer because updating react state outside react context (window events) was causing updates to always use the initial empty state

**before**:
status displayed as ready as in fact 2nd language needs training. user needed to change language for changes to be reflected
old-change

status of 2nd language not displayed 
old-need-training

**now** sorry for poor gif quality
now
here's a screencap
Screen Shot 2022-07-06 at 10 57 57 PM

closes #332
closes DEV-2552

### CODE REVIEW

File: packages/studio-ui/src/web/components/Layout/StatusBar/TrainingStatus/index.tsx [hunk 1]
```diff
@@ -1,32 +1,95 @@
...
+  event.type === 'nlu' && event.trainSession
+
 const TrainingStatusComponent: FC<Props> = (props: Props) => {
-  const { languages, trainSessions } = props
+  const { languages } = props
+  const [trainSessionsState, dispatch] = useReducer(trainStatusReducer, {})
 
-  if (!languages || languages.length < 1) {
-    return null
+  const onStatusBarEvent = (event: any) => {
```
Comment (laurentlp) [inline packages/studio-ui/src/web/components/Layout/StatusBar/TrainingStatus/index.tsx:39]: Can you use something other than `any` for the type of the argument?

File: packages/studio-ui/src/web/components/Layout/StatusBar/TrainingStatus/index.tsx [hunk 2]
```diff
@@ -1,32 +1,95 @@
...
+    if (isTrainStatusEvent(event) && event.botId === window.BOT_ID) {
+      dispatch({ type: 'setTrainSession', data: { trainSession: event.trainSession } })
+    }
   }
 
-  if (languages.length === 1) {
-    return <SingleLang trainSession={trainSessions[languages[0]]} />
+  const fetchTrainingSessionForLang = async (language: string) => {
```
Comment (laurentlp) [inline packages/studio-ui/src/web/components/Layout/StatusBar/TrainingStatus/index.tsx:45]: Can you add the return type here? I know that it's inferred, but adding it would make sure that we only expect this type to be returned.

File: packages/studio-ui/src/web/components/Layout/StatusBar/TrainingStatus/index.tsx [hunk 3]
```diff
@@ -1,32 +1,95 @@
...
+
+    Promise.map(languages, fetchTrainingSessionForLang)
+      .then((sessions) => {
+        const trainSessionBatchUpdate: Dictionary<NLU.TrainingSession> = {}
+        sessions.forEach((session) => {
+          trainSessionBatchUpdate[session.language] = session
+        })
+        dispatch({ type: 'setAllTrainSessions', data: trainSessionBatchUpdate })
+      })
+      .catch((err) => {})
```
Comment (laurentlp) [inline packages/studio-ui/src/web/components/Layout/StatusBar/TrainingStatus/index.tsx:78]: Add logging or a toast when there is an error fetching the training session?

**Review by laurentlp — APPROVED** [review]
Small comments otherwise LGTM! Nice work!!!

File: packages/studio-ui/src/web/components/Layout/StatusBar/TrainingStatus/MultiLang.tsx [hunk 4]
```diff
@@ -40,7 +40,9 @@ const MultiLangTrainingStatusComponent: FC<Props> = (props: Props) => {
 
   useEffect(() => {
     if (ready && popoverOpen) {
-      setTimeout(() => setPopoverOpen(false), 250)
+      // without timeout, it feels like the training is abrublty aborted
```
Comment (laurentlp) [inline packages/studio-ui/src/web/components/Layout/StatusBar/TrainingStatus/MultiLang.tsx:43]:
```suggestion
      // without timeout, it feels like the training is abruptly aborted
```

**Review by laurentlp — APPROVED** [review]
